#!/usr/bin/env node
/**
 * postinstall script for @netapp/seclab-apex
 *
 * Downloads MCP server binaries to ~/.apex/bin/ if not already cached.
 * Same artifacts and layout as the turnkey ontap-apex launcher.
 */

import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, chmodSync, renameSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

const APEX_HOME = process.env.APEX_HOME || join(homedir(), '.apex');
const BIN_DIR = join(APEX_HOME, 'bin');
const BASE_URL = 'https://generic.repo.eng.netapp.com/user/palanisd';

const artifacts = [
  {
    name: 'mastra-search-mcp',
    version: process.env.MASTRA_VERSION || 'latest',
    get url() {
      return `${BASE_URL}/mastra-search-mcp/${this.version}/mastra-search-mcp-linux-amd64.tar.gz`;
    },
    get dir() {
      return join(BIN_DIR, `mastra-search-mcp-${this.version}`);
    },
    get check() {
      return join(this.dir, 'mastra-search-mcp');
    },
    isTar: true,
  },
  {
    name: 'reviewboard-mcp',
    version: process.env.RB_VERSION || 'latest',
    get url() {
      return `${BASE_URL}/reviewboard-mcp/${this.version}/reviewboard-mcp.tar.gz`;
    },
    get dir() {
      return join(BIN_DIR, `reviewboard-mcp-${this.version}`);
    },
    get check() {
      return join(this.dir, 'index.js');
    },
    isTar: true,
  },
  {
    name: 'cit-mcp',
    version: process.env.CIT_VERSION || 'latest',
    get url() {
      return `${BASE_URL}/cit-mcp/${this.version}/cit-mcp-linux-amd64`;
    },
    get dest() {
      return join(BIN_DIR, `cit-mcp-${this.version}`);
    },
    get check() {
      return this.dest;
    },
    isTar: false,
  },
];

function download(url, dest, isTar) {
  const destDir = isTar ? dest : join(dest, '..');
  mkdirSync(destDir, { recursive: true });
  const tmp = join(destDir, '_download.tmp');
  try {
    execSync(`curl -fSL -o "${tmp}" "${url}"`, { stdio: 'pipe' });
    if (isTar) {
      mkdirSync(dest, { recursive: true });
      execSync(`tar xzf "${tmp}" -C "${dest}"`, { stdio: 'pipe' });
      rmSync(tmp, { force: true });
    } else {
      chmodSync(tmp, 0o755);
      renameSync(tmp, dest);
    }
    return true;
  } catch (_e) {
    rmSync(tmp, { force: true });
    return false;
  }
}

console.log('\n  APEX postinstall — checking MCP servers...\n');
mkdirSync(BIN_DIR, { recursive: true });

let downloaded = 0;
for (const art of artifacts) {
  if (existsSync(art.check)) {
    console.log(`  ✓ ${art.name} (cached)`);
    continue;
  }
  process.stdout.write(`  ⟳ ${art.name}...`);
  const target = art.isTar ? art.dir : art.dest;
  if (download(art.url, target, art.isTar)) {
    if (art.isTar && existsSync(art.check)) {
      chmodSync(art.check, 0o755);
    }
    console.log(' ✓');
    downloaded++;
  } else {
    console.log(' ✗ (failed — MCP server will be unavailable)');
  }
}

if (downloaded > 0) {
  console.log(`\n  Downloaded ${downloaded} MCP server(s) to ${BIN_DIR}`);
} else {
  console.log('\n  All MCP servers cached.');
}

// Generate ~/.apex/env.sh — sourceable file that derives all env vars from APEX_LLM_PROXY_KEY
import { writeFileSync as writeFile } from 'node:fs';
const D = '$';
const envSh = [
  '#!/bin/bash',
  '# Auto-generated by APEX postinstall — source this from ~/.bashrc',
  '# Only requires: export APEX_LLM_PROXY_KEY="user=<sso>&key=<key>"',
  '',
  '# Model API auth (derives from your proxy key)',
  `export ANTHROPIC_API_KEY="${D}APEX_LLM_PROXY_KEY"`,
  'export ANTHROPIC_BASE_URL="https://llm-proxy-api.ai.eng.netapp.com"',
  `export OPENAI_API_KEY="${D}APEX_LLM_PROXY_KEY"`,
  'export OPENAI_BASE_URL="https://llm-proxy-api.ai.eng.netapp.com"',
  '',
  '# Corp CA bundle',
  `if [ -z "${D}NODE_EXTRA_CA_CERTS" ]; then`,
  '  for ca in /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt; do',
  `    [ -f "${D}ca" ] && export NODE_EXTRA_CA_CERTS="${D}ca" && break`,
  '  done',
  'fi',
  '',
  '# MCP server paths',
  `export MASTRA_BIN="${D}HOME/.apex/bin/mastra-search-mcp-latest/mastra-search-mcp"`,
  `export MASTRA_NODE_PATH="${D}HOME/.apex/bin/mastra-search-mcp-latest/node_modules"`,
  `export RB_INDEX="${D}HOME/.apex/bin/reviewboard-mcp-latest/index.js"`,
  `export CIT_BIN="${D}HOME/.apex/bin/cit-mcp-latest"`,
  '',
].join('\n');
const envPath = join(APEX_HOME, 'env.sh');
writeFile(envPath, envSh);
console.log(`\n  Generated ${envPath}`);
console.log('  Add to ~/.bashrc:');
console.log('    export APEX_LLM_PROXY_KEY="user=<sso>&key=<key>"');
console.log(`    source ${envPath}\n`);
